# Site settings
author: Kyshon Gary
title: Growth and Prosperity
header-img: img/home-bg.png
email: kgarywork21@gmail.com
copyright_name: Kyshon Gary
description: > # this means to ignore newlines until "baseurl:"
  Why I want to become a software engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kyshongary

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
